version: '3.6'

services:
  tests:
    build:
      context: .
      target: build
    depends_on:
      - imgr_db
      - auth_db
    env_file:
      - .env.test

  imgr_db:
    image: postgres:10.3-alpine
    volumes:
      - imgr_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: imgr

  auth_db:
    image: postgres:10.3-alpine
    volumes:
      - auth_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: auth

volumes:
  imgr_db:
  auth_db:
