version: '3.6'

services:
  tests:
    build:
      context: .
      target: build
    depends_on:
      - postgres
    volumes:
    - ./wait-for:./wait-for
    env_file:
      - .env.test

  postgres:
    image: postgres:10.3-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'test'

volumes:
  db:
