version: '3.6'

services:
  images:
    build:
      context: .
      target: images
    restart: unless-stopped
    command: sh -c './wait-for postgres_images:5432 -- ./app'
    expose:
      - 3000
    depends_on:
      - postgres_images
    volumes:
      - static:/static
    env_file:
      - .env.common
      - .env.images

  auth:
    build:
      context: .
      target: auth
    restart: unless-stopped
    command: sh -c './wait-for postgres_auth:5432 -- ./app'
    expose:
      - 3000
    depends_on:
      - postgres_auth
    env_file:
      - .env.common
      - .env.auth

  nginx:
    image: nginx:1.13-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - images
      - auth
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  postgres_auth:
    image: postgres:10.3-alpine
    restart: unless-stopped
    volumes:
      - db_auth:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'auth'

  postgres_images:
    image: postgres:10.3-alpine
    restart: unless-stopped
    volumes:
      - db_images:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'images'

volumes:
  db_images:
  db_auth:
  static:
