version: '3.6'

services:
  imgr:
    build:
      context: .
      target: imgr
    restart: unless-stopped
    command: sh -c './wait-for postgres_imgr:5432 -- ./app'
    expose:
      - 3000
    depends_on:
      - postgres_imgr
    volumes:
      - ./wait-for:./wait-for
      - static:/static
    env_file:
      - .env.common
      - .env.imgr

  auth:
    build:
      context: .
      target: auth
    restart: unless-stopped
    command: sh -c './wait-for postgres_auth:5432 -- ./app'
    expose:
      - 3000
    depends_on:
      - postgres_auth
    volumes:
      - ./wait-for:./wait-for
    env_file:
      - .env.common
      - .env.auth

  nginx:
    image: nginx:1.13-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - imgr
      - auth
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  postgres_auth:
    image: postgres:10.3-alpine
    restart: unless-stopped
    volumes:
      - db_auth:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'auth'

  postgres_imgr:
    image: postgres:10.3-alpine
    restart: unless-stopped
    volumes:
      - db_imgr:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'imgr'

volumes:
  db_imgr:
  db_auth:
  static:
