[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "0.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "goji.io"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/gavv/httpexpect.v1"

# Fix httpexpect dependencies
[[override]]
  branch = "master"
  name = "github.com/valyala/fasthttp"


[prune]
  go-tests = true
  unused-packages = true
